---
title: "Clean Raw Landsat"
author: "Madeline Berger"
date: "2025-07-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages 

library(terra) # for rasters
library(sf) # for vector data
library(tidyverse)
library(here) # I use this to easily create relative file paths

# set file path to data folder 

oahu_raw_data <- here("low_resolution/oahu")

zoning <- here("low_resolution/honolulu_zoning")


```

Read in one raster and convert to data frame (as an example). Read in and look at zoning shapefile

```{r}


first_rast <- terra::rast(file.path(oahu_raw_data,"Oahu_2014_LS8_composite_low_resolution.tif")) #read in the tif file as a SpatRaster using terra

first_rast # get summary of whats in the raster

nlyr(first_rast) # there are the bands

# what happens when we run as data frame


first_df <- as.data.frame(first_rast, xy = T)

#read in zoning

zones_raw <- read_sf(file.path(zoning,"Zoning.shp"))

# quick visualize
library(mapview)

mapview(zones_raw, zcol = "zone_class")


```

Convert shapefiles to raster using the "zones_class" 

```{r}

st_crs(zones_raw) #hi zone 3 

# convert to match raster

zones_wgs84 <- st_transform(zones_raw, crs = crs(first_rast))

# create raster template from landsat raster
r_temp <- rast(first_rast)

zones_rast <- rasterize(zones_wgs84, r_temp, field = "zone_class")


plot(zones_rast)

# make sure its origin and extent are aligned with landsat rasters 


ext_landsat <- ext(first_rast)
ext_zones <- ext(zones_rast)

origin_landsat <- origin(first_rast)
origin_zones <- origin(zones_rast)


res(first_rast) == res(zones_rast) # check if true

# convert zones rast to df to join to land use df

zones_rast_df <- as.data.frame(zones_rast, xy = T)

```





Loop to read in each raster and convert to data frame. The steps will:
- run through each file and read it in as a Spat Raster
- create a df of each
- save each one in a list with a new column for year

```{r}

# list each landsat raster

tif_files <- list.files(oahu_raw_data,
                        pattern = ".tif")

# create empty list

df_list <- list()

for (i in 1:length(tif_files)){
  
  # for testing
  #i = 1
  
  # file name
  f = tif_files[i]
  
  # get year from file name
  year = substr(f,6,9)
  
  # read in raster
  rast = terra::rast(file.path(oahu_raw_data,f))
  
  # convert to df, add column with year
  
  df <- as.data.frame(rast, xy = T) %>% mutate(image_year = rep(year, nrow(.)))
  
  df_with_zones <- left_join(df, zones_rast_df, by = c("x","y")) %>% 
    filter(!is.na(zone_class))
  
  # save to list 

  df_list[[i]] <- df_with_zones
  
}


# now we have a list of dfs with band values, year and the zone it falls into for each pixel


# for visulizaing if this work 
df_zones_sf <- st_as_sf(df_with_zones, coords = c("x","y"))

plot(df_zones_sf)

```

